"""
BaseWethUsdcMomentum Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import BaseWethUsdcMomentumStrategy
except ImportError:
    from strategy import BaseWethUsdcMomentumStrategy

__all__ = [
    "BaseWethUsdcMomentumStrategy",
]
